# Generated by Django 5.1 on 2024-08-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_data', '0015_alter_team_options_alter_venue_options_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField(blank=True, null=True)),
                ('away', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(blank=True, null=True)),
                ('second', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(blank=True, max_length=16, null=True)),
                ('short', models.CharField(blank=True, max_length=16, null=True)),
                ('elapsed', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('logo', models.URLField(blank=True, max_length=128, null=True)),
                ('flag', models.URLField(blank=True, max_length=128, null=True)),
                ('round', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='football_data.country')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extratime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_time', to='fixtures.goals')),
                ('full_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_time', to='fixtures.goals')),
                ('half_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='half_time', to='fixtures.goals')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_time', to='fixtures.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('referee', models.CharField(blank=True, max_length=64, null=True)),
                ('timezone', models.CharField(blank=True, max_length=16, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_away', to='football_data.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_home', to='football_data.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='football_data.venue')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='fixtures.league')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='fixtures.period')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.status')),
            ],
        ),
    ]
