# Generated by Django 5.1 on 2024-08-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='Period',
            new_name='Periods',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
