# Generated by Django 5.1 on 2024-08-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_rename_period_fixture_periods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='periods',
            options={'verbose_name_plural': 'Periods'},
        ),
    ]
