# Generated by Django 5.1 on 2024-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_alter_fixture_options_alter_periods_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['long'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
