# Generated by Django 5.1 on 2024-08-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_alter_fixture_away_team_alter_fixture_home_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name']},
        ),
    ]
