# Generated by Django 5.1 on 2024-08-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0002_alter_country_code_alter_country_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=256, unique=True)),
                ('last_requested', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Endpoints',
            },
        ),
    ]
