# Generated by Django 5.1 on 2024-08-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0003_endpointtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointtracker',
            name='last_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
