# Generated by Django 5.1 on 2024-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0007_alter_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
