# Generated by Django 5.1 on 2024-08-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0010_alter_team_code_alter_team_founded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='football_data.season'),
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football_data.venue'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_data.country'),
        ),
    ]
