# Generated by Django 5.1 on 2024-08-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0011_team_seasons_team_venue_alter_team_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(related_name='teams', to='football_data.season'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('firstname', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=64, null=True)),
                ('height', models.CharField(blank=True, max_length=64, null=True)),
                ('weight', models.CharField(blank=True, max_length=64, null=True)),
                ('national', models.BooleanField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('country', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_data.country')),
                ('nationality', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='football_data.country')),
                ('seasons', models.ManyToManyField(related_name='players', to='football_data.season')),
            ],
        ),
    ]
