# Generated by Django 5.1 on 2024-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0013_alter_player_country_alter_player_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
