# Generated by Django 5.1 on 2024-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0015_alter_team_options_alter_venue_options_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
