# Generated by Django 5.1 on 2024-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0016_alter_venue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_id',
            field=models.IntegerField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
