# Generated by Django 5.1 on 2024-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0017_venue_venue_id_alter_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
