# Generated by Django 5.1 on 2024-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0019_alter_season_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.RemoveField(
            model_name='team',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='team',
            name='venue',
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
