# Generated by Django 5.1 on 2024-08-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_alter_fixture_away_team_alter_fixture_home_team_and_more'),
        ('football_data', '0020_remove_team_country_remove_team_seasons_and_more'),
        ('players', '0011_alter_player_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
