# Generated by Django 5.1 on 2024-08-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_data', '0015_alter_team_options_alter_venue_options_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('firstname', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=64, null=True)),
                ('weight', models.CharField(blank=True, max_length=64, null=True)),
                ('national', models.BooleanField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football_data.country')),
                ('seasons', models.ManyToManyField(related_name='players', to='football_data.season')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=64, null=True)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='football_data.country')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
            ],
            options={
                'ordering': ['player'],
            },
        ),
    ]
