# Generated by Django 5.1 on 2024-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
