# Generated by Django 5.1 on 2024-08-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='national',
        ),
    ]
