# Generated by Django 5.1 on 2024-08-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0015_alter_team_options_alter_venue_options_delete_player'),
        ('players', '0005_remove_player_national'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth',
            old_name='birth_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='birth',
            old_name='birth_place',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='birth',
            name='nationality',
        ),
        migrations.AddField(
            model_name='birth',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth', to='football_data.country'),
        ),
        migrations.AddField(
            model_name='player',
            name='notionality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='football_data.country'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth', to='players.player'),
        ),
    ]
