# Generated by Django 5.1 on 2024-08-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_rename_birth_date_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
