# Generated by Django 5.1 on 2024-08-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_injured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='notionality',
            new_name='nationality',
        ),
    ]
