# Generated by Django 5.1 on 2024-08-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_rename_notionality_player_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birth',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='birth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='birth',
            name='player',
        ),
        migrations.AddField(
            model_name='birth',
            name='player',
            field=models.ManyToManyField(related_name='birth', to='players.player'),
        ),
    ]
