# Generated by Django 5.1 on 2024-08-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_birth_options_alter_birth_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birth',
            name='player',
        ),
        migrations.AddField(
            model_name='birth',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
